---
title: "velib"
author: "Nicolas"
date: "22/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())   # erase everything, start from scratch!

# load the data from package funFEM

library(funFEM)
library(FactoMineR)
library(factoextra)
library(ggplot2)
```


```{r}
velib = read.csv("velibLoading.csv", sep = " ")
velibAdds = read.csv("velibAdds.csv", sep = " ")
str(velibAdds)
#str(velib)
```

```{r}
x <- as.matrix(velib)
```



```{r}
velib.pca <- PCA(x, scale=TRUE, ncp=15)
```

```{r}
get_eigenvalue(velib.pca)[1:15,]
```

```{r}
fviz_eig(velib.pca, addlabels = TRUE,ncp=15)
```

```{r}
boxplot(velib.pca$ind$coord,ylim=c(-7,7),
        xlab = "Number of the principal axis",
        ylab = "Coordinate on the principal axis")
```

```{r}
get_pca_var(velib.pca)$coord[, 1:4]
```

```{r}
timeTick <- 1 + 24*(0:6)
dim = get_pca_var(velib.pca)$coord
options(repr.plot.width = 15, repr.plot.height = 15)
par(mfrow=c(4,1))
for (i in 1:4){
    plot(dim[,i], col = "blue", type = "l", ylim = c(0, 1), 
     xlab = "Time", ylab = "dim", main = rownames(x)[i])
    abline(v = timeTick, lty = "dotted")
}
```

```{r}
fviz_pca_var(velib.pca,axes=c(1,2), col.var = "cos2",
            gradient.cols = c("blue","yellow","red"),
            repel = TRUE)

fviz_pca_var(velib.pca,axes=c(1,3), col.var = "cos2",
            gradient.cols = c("blue","yellow","red"),
            repel = TRUE)

fviz_pca_var(velib.pca,axes=c(2,3), col.var = "cos2",
            gradient.cols = c("blue","yellow","red"),
            repel = TRUE)

fviz_pca_var(velib.pca,axes=c(3,4), col.var = "cos2",
            gradient.cols = c("blue","yellow","red"),
            repel = TRUE)
```

Les heures correspondant aux flèches bleues sont principalement les nuits du week-end (0-3h), les flèches jaunes, qui se trouvent dans la même région que les flèches bleues mais plus longues, sont l'après-midi du jour de la semaine (13-17h), et les flèches rouges sous l'axe horizontal est principalement les matins du jour de la semaine (4-5h).

```{r}
options(repr.plot.width = 8, repr.plot.height = 8)
fviz_pca_ind(velib.pca,geom="point",
             col.ind = "cos2", # Colorer par le cos2
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), repel = FALSE)

options(repr.plot.width = 8, repr.plot.height = 8)
fviz_pca_ind(velib.pca,col.ind = "contrib", 
             gradient.cols = c("#00AFBB","#E7B800","#FC4E07"),repel = FALSE)

fviz_pca_biplot(velib.pca, repel = FALSE,
                col.var = "#2E9FDF",
                col.ind = "#696969")

```

## Clustering

```{r}
xbrut <- as.matrix(velib)
kmbrut <- kmeans(xbrut,5, nstart=10)

str(kmbrut)
```

```{r}
data_brut <- kmbrut$cluster
groupe_brut = unname(data_brut)

print((data_brut == 1)*1)


sol = cbind(velibAdds$longitude,velibAdds$latitude,groupe_brut)
sol = data.frame(sol)

str(sol)
plot(c(velibAdds$longitude,velibAdds$latitude))
```



```{r}
fviz_cluster(kmbrut,data=xbrut)
options(repr.plot.width = 15, repr.plot.height = 15)

velib.pca$ind$coord
```

```{r}
xbrut_pca <- as.matrix(get_pca_ind(velib.pca)$coord)[,1:5]
kmbrut_pca <- kmeans(xbrut_pca,5, nstart=10)
fviz_cluster(kmbrut_pca,data=xbrut_pca)

xvarbrut_pca <- as.matrix(get_pca_var(velib.pca)$coord)[,1:5]
kmvarbrut_pca <- kmeans(xvarbrut_pca,5, nstart=10)
fviz_cluster(kmvarbrut_pca,data=xvarbrut_pca)
```





































